url: https://aisgaiap.blob.core.windows.net/aiap5-assessment-data/traffic_data.csv

to_drop: True
drop_list: ['snow_1h','rain_1h','clouds_all','weather_description']

train_test_split:
  split_by_time: False
  test_size: 0.3
  random_state: 42

eval_metric:
  to_round: True
  rounding_decimals: 3
  show_mae: True
  show_mse: True
  show_r2: True
  do_cv: True
  cv_folds: 5
  cv_scoring: 'r2_score'

models:
  LinearRegression: True
  RandomForestRegressor: False
  LGBMRegressor: True

LinearRegression:
  n_jobs: -1

RandomForest:
  n_estimators: 200
  criterion: mse
  max_depth: !!python/none
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_features: auto
  max_leaf_nodes: !!python/none
  min_impurity_decrease: 0.0
  min_impurity_split: !!python/none
  bootstrap: True
  oob_score: False
  n_jobs: -1
  random_state: 42
  verbose: 0

LightGBM:
    boosting_type: gbdt
    num_leaves: 31
    max_depth: -1
    learning_rate: 0.1
    n_estimators: 1000
    subsample_for_bin: 200000
    objective: !!python/none
    class_weight: !!python/none
    min_split_gain: 0.0
    min_child_weight: 0.001
    min_child_samples: 20
    subsample: 1.0
    subsample_freq: 0
    colsample_bytree: 1.0
    reg_alpha: 0.0
    reg_lambda: 0.0
    random_state: 42
    n_jobs: -1
    silent: True
    importance_type: split